from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader

from .env_utils import ensure_secret, parse_env_file, write_env_file


REQUIRED_ENV_KEYS = ["POSTGRES_PASSWORD", "VLLM_API_KEY", "HF_TOKEN"]


def _template_env(template_dir: Path) -> Environment:
    return Environment(
        loader=FileSystemLoader(str(template_dir)),
        trim_blocks=True,
        lstrip_blocks=True,
    )


def _ensure_output_dirs(plan: dict[str, Any]) -> None:
    for key in ("storage_root", "hf_cache_dir", "openwebui_data_dir", "postgres_data_dir"):
        value = plan.get("paths", {}).get(key)
        if value:
            Path(value).mkdir(parents=True, exist_ok=True)


def _prepare_env_file(plan: dict[str, Any], env_path: Path) -> dict[str, str]:
    existing = parse_env_file(env_path)
    env = {k: existing.get(k, "") for k in REQUIRED_ENV_KEYS}
    ensure_secret(env, "POSTGRES_PASSWORD")
    ensure_secret(env, "VLLM_API_KEY")
    ensure_secret(env, "HF_TOKEN", blank_ok=True)
    write_env_file(
        env_path,
        env,
        comments=[
            "Autogenerated by python manage.py render",
            "POSTGRES_PASSWORD and VLLM_API_KEY are preserved after first creation",
            "HF_TOKEN can be left blank for public models",
        ],
    )
    return env


def render_files(plan: dict[str, Any], output_dir: str | Path, template_dir: str | Path) -> dict[str, Path]:
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    template_path = Path(template_dir)
    env = _template_env(template_path)
    _ensure_output_dirs(plan)

    env_file = output_path / ".env"
    _prepare_env_file(plan, env_file)

    compose_text = env.get_template("docker-compose.yml.j2").render(plan=plan)

    compose_file = output_path / "docker-compose.yml"
    plan_file = output_path / "plan.json"

    compose_file.write_text(compose_text + "\n", encoding="utf-8")
    plan_file.write_text(json.dumps(plan, indent=2) + "\n", encoding="utf-8")

    return {
        "compose": compose_file,
        "env": env_file,
        "plan": plan_file,
    }
