[remmina]
disableclipboard=0
ssh_auth=0
clientname=
quality=0
ssh_charset=
ssh_privatekey=
console=0
resolution=1800x900
group=
password=supersecretpassword==
name=HostNameZeusCannon
ssh_loopback=0
shareprinter=0
ssh_username=
ssh_server=
security=
protocol=RDP
execpath=
sound=off
exec=
ssh_enabled=0
username=myusername@gmail.com
sharefolder=
domain=
server=192.168.13.106
colordepth=32
window_maximize=0
window_height=967
viewmode=1
window_width=1812
~         