#!/bin/sh
export QT_ACCESSIBILITY=0

if [[ "$OSTYPE" == "darwin"* ]]; then
    export NCPUS=$(sysctl -n hw.ncpu)
    source ~/local/homelinks/helpers/bashrc_mac.sh
else
    export NCPUS=$(grep -c ^processor /proc/cpuinfo)
    source ~/local/homelinks/helpers/bashrc_ubuntu
fi

export QT_API=pyqt


# My standard environment variables
if [[ "$HOSTNAME" == "ibeis.cs.uic.edu"  ]]; then 
    export CODE_DIR=/opt/ibeis
elif [[ "$HOSTNAME" == "pachy.cs.uic.edu"  ]]; then 
    export CODE_DIR=/opt/ibeis
else
    export CODE_DIR=~/code
fi

export PYTHONPATH=$CODE_DIR/utool:$PYTHONPATH
export PYTHONPATH=$HOME/local/pyscripts:$PYTHONPATH


export PYTHON_VENV="$HOME/venv2"
#echo $PYTHON_VENV
# Activate a virtual environment
if [ -d "$PYTHON_VENV" ]; then
    source $PYTHON_VENV/bin/activate
fi

setup_venv2(){
    # ENSURE SYSTEM PIP IS SAME AS SYSTEM PYTHON
    # sudo update-alternatives --set pip /usr/local/bin/pip2.7
    # sudo rm /usr/local/bin/pip
    # sudo ln -s /usr/local/bin/pip2.7 /usr/local/bin/pip

    export PYTHON2_VENV="$HOME/venv2"
    mkdir $PYTHON2_VENV
    virtualenv -p /usr/bin/python2.7 $PYTHON2_VENV 
    #virtualenv --relocatable $PYTHON2_VENV 
}
setup_venv3(){
    sudo pip3 install virtualenv
    sudo pip3 install virtualenv -U
    export PYTHON3_VENV="$HOME/venv3"
    mkdir -p $PYTHON3_VENV
    virtualenv -p /usr/bin/python3 $PYTHON3_VENV
    virtualenv --relocatable $PYTHON3_VENV 
    # source $PYTHON3_VENV/bin/activate
}


#export OMP_NUM_THREADS=7

source ~/local/homelinks/helpers/git_helpers
source ~/local/homelinks/helpers/alias_helpers

update_pip_dists()
{
    sudo pip install pyinstaller --upgrade
}
 
permit_erotemic_gitrepo()
{ 
    #permit_gitrepo -i
    sed -i 's/https:\/\/github.com\/Erotemic/git@github.com:Erotemic/' .git/config
    #sed -i 's/https:\/\/github.com\/bluemellophone/git@github.com:bluemellophone/' .git/config
    #sed -i 's/https:\/\/github.com\/zmjjmz/git@github.com:zmjjmz/' .git/config
    #sed -i 's/https:\/\/github.com\//git@github.com:' .git/config
}


# set history to not ignore leading whitespace
export HISTCONTROL=


export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

# If IBM CPLEX is installed
export CPLEX_PREFIX=/opt/ibm/ILOG/CPLEX_Studio_Community1263
export PATH=$PATH:$CPLEX_PREFIX/cplex/bin/x86-64_linux/
export PATH=$PATH:$CPLEX_PREFIX/opl/oplide/
export PATH=$PATH:$CPLEX_PREFIX/cplex/include/
export PATH=$PATH:$CPLEX_PREFIX/opl/include/
export PATH=$PATH:$CPLEX_PREFIX/opl/

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CPLEX_PREFIX/cplex/lib/x86-64_linux/static_pic
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CPLEX_PREFIX/cplex/bin/x86-64_linux/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CPLEX_PREFIX/opl/bin/x86-64_linux
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CPLEX_PREFIX/opl/lib/x86-64_linux/static_pic


# For vigra
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VIRTUAL_ENV/lib



# Add CUDA to the library paths if it exists
if [ -d "/usr/local/cuda" ]; then
    # Use the symlinked version if available
    export PATH=$PATH:/usr/local/cuda/bin
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
elif [ -d "/usr/local/cuda" ]; then
    # Use an explicit version if available
    export PATH=$PATH:/usr/local/cuda7.5/bin
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda7.5/lib64
fi

# Other program environment variables
if [[ "$HOSTNAME" == "hyrule"  ]]; then 
    #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/lib
    #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-7.5/targets/x86_64-linux/lib:/usr/local/lib
    #export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
    # hacky
    #export TOMCAT_DIR=$CODE_DIR/Wildbook/tmp/apache-tomcat-8.0.24
    #export TOMCAT_HOME=$TOMCAT_DIR
    #export CATALINA_HOME=$TOMCAT_DIR
    export PATH=/usr/local/texlive/2015/bin/x86_64-linux:$PATH
elif [[ "$HOSTNAME" == "dozer"  ]]; then 
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-6.5/lib64:/usr/local/lib
    export PATH=$PATH:/usr/local/cuda-6.5/bin
elif [[ "$HOSTNAME" == "Ooo"  ]]; then 
    #export UTOOL_NO_PYRF=True
    export UTOOL_NO_PYRF=False
    export UTOOL_NO_CNN=False
    export THEANO_FLAGS="device=cpu"

    export PATH=$PATH:/opt/gurobi650/linux64/bin
    #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/gurobi650/linux64/lib
    export PATH=/usr/local/texlive/2015/bin/x86_64-linux:$PATH
else
    # These paths are likely to be true on other machines as weel
    #export PATH=$PATH:/usr/local/cuda/bin
    #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/lib
    #export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
    export PATH=$PATH
fi

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PYTHON_VENV/lib

# hack
#export UTOOL_DPATH=~/latex/crall-candidacy-2015/

complete -W "gp focus kill project_dpaths sync_clipboard_to grepnr printproc_2 send add_path write_env print_path grepc grepr grep research_clipboard fix_path foo fixpath2 write_rob_pathcache sed reg_disable_automatic_reboot_122614 find write_regfile pykill symlink update_path printproc_ write_path search update_env make_dpath invgrep send_command research ps send_clipboard_to make_complete pref_env print_env create_shortcut info hskill process_research_line write_research find_in_path get_regstr preprocess_research sedr update setup_global sp print_clipboard upenv fix_youtube_names_ccl dump_clipboard" "rob"

#set bell-style none
#xset -b
#setterm -blength 0
#gconftool-2 --set --type=bool /apps/metacity/general/audible_bell false
#gconftool-2 --get  /apps/metacity/general/audible_bell

#source ~/.config/ibeis/ibeis_bash_complete.sh
