services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /data/service/docker/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all

    restart: unless-stopped
    environment:
      - OLLAMA_LOG_LEVEL=debug
      - OLLAMA_KEEP_ALIVE=99999h
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "${OPENWEBUI_PORT:-14771}:8080"
    environment:
      - WEBUI_AUTH=False
      #- OLLAMA_BASE_URL=http://host.docker.internal:11434
      # Talk to the service name directly
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - /data/service/docker/open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_models:
    driver: local
    driver_opts:
      type: none
      device: /data/service/docker/ollama
      o: bind
  open_webui_data:
    driver: local
    driver_opts:
      type: none
      device: /data/service/docker/open-webui
      o: bind
